<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="HtmlTemplates\navbar.js" />
    <None Remove="HtmlTemplates\styles.css" />
    <None Remove="HtmlTemplates\treeLogic.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="HtmlTemplates\navbar.js" />
    <EmbeddedResource Include="HtmlTemplates\styles.css" />
    <EmbeddedResource Include="HtmlTemplates\treeLogic.js" />
  </ItemGroup>

</Project>
